name: Deploy
on:
  push:
    branches:
      - main
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          touch ~/.ssh/known_hosts

      - name: Verify SSH connection
        run: ssh-keyscan -H ${{secrets.HOST}} >> ~/.ssh/known_hosts

      - name: Connect to VSP
        run: sshpass -p ${{secrets.PASSWORD}} ssh chirag@${{secrets.HOST}} 'echo "Connected to VSP successfully!" && pwd'
        run: git clone https://github.com/Chirag482/test.git
        run: cd marengo_client
        run: 'echo pwd && ls'


